{
 "title": "Elasticsearch - Node Stats",
 "tags": [
  "elasticsearch",
  "es-cluster-node"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(elasticsearch_indices_docs,cluster)"
   },
   {
    "name": "instance",
    "label": "Source of metrics",
    "query": "label_values(elasticsearch_indices_docs{cluster=\"$cluster\", name!=\"\"},instance)"
   },
   {
    "name": "name",
    "label": "Node name",
    "query": "label_values(elasticsearch_indices_docs{instance=\"$instance\",cluster=\"$cluster\", name!=\"\"},name)"
   },
   {
    "name": "interval",
    "label": "Rate Interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Documents",
   "type": "singlestat",
   "description": "On primary shards",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_docs{instance=\"$instance\",cluster=\"$cluster\",name=\"$name\"})"
    }
   ]
  },
  {
   "title": "Data",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_store_size_bytes{instance=\"$instance\",cluster=\"$cluster\",name=\"$name\"})"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (elasticsearch_jvm_memory_used_bytes{instance=\"$instance\",cluster=\"$cluster\",name=\"$name\"})"
    }
   ]
  },
  {
   "title": "Segments",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (elasticsearch_indices_segments_count{instance=\"$instance\",cluster=\"$cluster\",name=\"$name\"})"
    }
   ]
  },
  {
   "title": "Open Fds",
   "type": "singlestat",
   "description": "Open file descriptors",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_process_open_files_count{instance=\"$instance\",cluster=\"$cluster\",name=\"$name\"})"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (elasticsearch_jvm_memory_used_bytes{instance=\"$instance\",cluster=\"$cluster\",name=\"$name\"}) / \nsum (elasticsearch_jvm_memory_max_bytes{instance=\"$instance\",cluster=\"$cluster\",name=\"$name\"}) * 100"
    }
   ]
  },
  {
   "title": "% Disk Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - \nsum (elasticsearch_filesystem_data_available_bytes{instance=\"$instance\",cluster=\"$cluster\",name=\"$name\"}) / \nsum (elasticsearch_filesystem_data_size_bytes{instance=\"$instance\",cluster=\"$cluster\",name=\"$name\"}) * 100"
    }
   ]
  },
  {
   "title": "% CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (elasticsearch_os_cpu_percent{instance=~\"$instance\",name=\"$name\"})"
    }
   ]
  },
  {
   "title": "JVM Max Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (elasticsearch_jvm_memory_pool_max_bytes{instance=\"$instance\",cluster=\"$cluster\",name=\"$name\"})"
    }
   ]
  },
  {
   "title": "Segment Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_segments_memory_bytes{instance=\"$instance\",cluster=\"$cluster\",name=\"$name\"})"
    }
   ]
  },
  {
   "title": "Max Fds",
   "type": "singlestat",
   "description": "Max open file descriptors",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_process_max_files_descriptors{instance=\"$instance\",cluster=\"$cluster\",name=\"$name\"})"
    }
   ]
  },
  {
   "title": "Node Roles",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (name) (elasticsearch_nodes_roles{role=\"master\",name=\"$name\"})",
     "legendFormat": "Master Node"
    },
    {
     "expr": "sum by (name) (elasticsearch_nodes_roles{role=\"data\",name=\"$name\"})",
     "legendFormat": "Data Node"
    },
    {
     "expr": "sum by (name) (elasticsearch_nodes_roles{role=\"ingest\",name=\"$name\"})",
     "legendFormat": "Ingest Node"
    },
    {
     "expr": "sum by (name) (elasticsearch_nodes_roles{role=\"client\",name=\"$name\"})",
     "legendFormat": "Client Node"
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_filesystem_data_available_bytes{instance=\"$instance\",cluster=\"$cluster\",name=\"$name\"})"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Indexing rate on $name",
   "type": "graph",
   "description": "Indexing rate on node\n\n`ProcRate`: processing ability, which is the number of requests that Elasticsearch can handle. Estimation is based on the processed requests and processed time for these requests.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "reqps", "label": "ReqRate" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "ReqRate"
    },
    {
     "expr": "1 / \n(\nrate(elasticsearch_indices_indexing_index_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval]) / \nrate(elasticsearch_indices_indexing_index_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])\n)",
     "legendFormat": "ProcRate"
    }
   ]
  },
  {
   "title": "Searching rate on $name",
   "type": "graph",
   "description": "Searching rate on node\n\n`ProcRate`: processing ability, which is the number of requests that Elasticsearch can handle. Estimation is based on the processed requests and processed time for these requests.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "reqps", "label": "ReqRate" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_search_query_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "ReqRate"
    },
    {
     "expr": "1 / (\n(rate(elasticsearch_indices_search_query_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])\n+ rate(elasticsearch_indices_search_fetch_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])\n+ rate(elasticsearch_indices_search_scroll_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])\n+ rate(elasticsearch_indices_search_suggest_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])\n) / \nrate(elasticsearch_indices_search_query_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])\n)",
     "legendFormat": "ProcRate"
    }
   ]
  },
  {
   "title": "All Operations ReqRate on $name",
   "type": "graph",
   "description": "Stacked by y-axis",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Indexing"
    },
    {
     "expr": "rate(elasticsearch_indices_search_query_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Search Query"
    },
    {
     "expr": "rate(elasticsearch_indices_search_fetch_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Search Fetch"
    },
    {
     "expr": "rate(elasticsearch_indices_merges_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Merges"
    },
    {
     "expr": "rate(elasticsearch_indices_refresh_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Refresh"
    },
    {
     "expr": "rate(elasticsearch_indices_flush_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Flush"
    },
    {
     "expr": "rate(elasticsearch_indices_get_exists_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Get exists"
    },
    {
     "expr": "rate(elasticsearch_indices_get_missing_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Get missing"
    },
    {
     "expr": "rate(elasticsearch_indices_get_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Get"
    },
    {
     "expr": "rate(elasticsearch_indices_indexing_delete_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Indexing delete"
    },
    {
     "expr": "rate(elasticsearch_indices_search_scroll_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Search Scroll"
    },
    {
     "expr": "rate(elasticsearch_indices_search_suggest_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Search Suggest"
    }
   ]
  },
  {
   "title": "All Operations Runtime / s on $name",
   "type": "graph",
   "description": "Stacked by y-axis",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Indexing"
    },
    {
     "expr": "rate(elasticsearch_indices_search_query_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Search Query"
    },
    {
     "expr": "rate(elasticsearch_indices_search_fetch_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Search Fetch"
    },
    {
     "expr": "rate(elasticsearch_indices_merges_total_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Merges"
    },
    {
     "expr": "rate(elasticsearch_indices_refresh_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Refresh"
    },
    {
     "expr": "rate(elasticsearch_indices_flush_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Flush"
    },
    {
     "expr": "rate(elasticsearch_indices_get_exists_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Get exists"
    },
    {
     "expr": "rate(elasticsearch_indices_get_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Get time"
    },
    {
     "expr": "rate(elasticsearch_indices_get_missing_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Get missing"
    },
    {
     "expr": "rate(elasticsearch_indices_indexing_delete_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Indexing delete"
    },
    {
     "expr": "rate(elasticsearch_indices_get_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Get"
    },
    {
     "expr": "rate(elasticsearch_indices_search_scroll_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Search Scroll"
    },
    {
     "expr": "rate(elasticsearch_indices_search_suggest_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Search Suggest"
    },
    {
     "expr": "rate(elasticsearch_indices_merges_total_throttled_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Merges Thorttle"
    },
    {
     "expr": "rate(elasticsearch_indices_indexing_throttle_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Indexing Throttle"
    }
   ]
  },
  {
   "title": "Search Rate (req/s) on $name",
   "type": "graph",
   "description": "Stacked by y-axis",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_search_query_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Query"
    },
    {
     "expr": "rate(elasticsearch_indices_search_fetch_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Fetch"
    },
    {
     "expr": "rate(elasticsearch_indices_search_scroll_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Scroll"
    },
    {
     "expr": "rate(elasticsearch_indices_search_suggest_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Suggest"
    }
   ]
  },
  { "title": "Index Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Index Memory - Lucene - $name",
   "type": "graph",
   "description": "+ *Lucene Total*: Total heap memory used by Lucene for current index. This is the sum of other fields for primary and replica shards on this node.\n\n+ *Stored Fields*: Heap memory used by Stored Fields (e.g., _source). This is a part of Lucene Total.. \n\n+ *Doc Values*: Heap memory used by Doc Values. This is a part of Lucene Total.. \n\n+ *Norms*: Heap memory used by Norms (normalization factors for query-time, text scoring). This is a part of Lucene Total.\n\n+ *Terms*: (e.g., text). This is a part of Lucene Total.\n\n+ *Points*: Heap memory used by Points (e.g., numbers, IPs, and geo data). This is a part of Lucene Total.\n\n+ *Fixed Bitsets*: (e.g., text). This is a part of Lucene Total.\n\n+ *Term Vectors*: Heap memory used by Term Vectors. This is a part of Lucene Total.\n\n+ *Version Map*: Heap memory used by Versioning (e.g., updates and deletes). This is NOT a part of Lucene Total.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segments_stored_fields_memory_in_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Stored Fields"
    },
    {
     "expr": "elasticsearch_indices_segments_doc_values_memory_in_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Doc Values"
    },
    {
     "expr": "elasticsearch_indices_segments_norms_memory_in_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Norms"
    },
    {
     "expr": "elasticsearch_indices_segments_fixed_bit_set_memory_in_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Fixed Bitsets"
    },
    {
     "expr": "elasticsearch_indices_segments_term_vectors_memory_in_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Term Vectors"
    },
    {
     "expr": "elasticsearch_indices_segments_version_map_memory_in_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Version Map"
    },
    {
     "expr": "elasticsearch_indices_segments_terms_memory_in_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Terms"
    },
    {
     "expr": "elasticsearch_indices_segments_points_memory_in_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Points"
    },
    {
     "expr": "elasticsearch_indices_segments_memory_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Lucene Total"
    }
   ]
  },
  {
   "title": "Index Memory - Elasticsearch - $name",
   "type": "graph",
   "description": "+ *Query Cache*: Heap memory used by Query Cache (e.g., cached filters). This is for the same shards, but not a part of Lucene Total.. \n\n+ *Request Cache*: Heap memory used by Request Cache (e.g., instant aggregations). This is for the same shards, but not a part of Lucene Total.. \n\n+ *Fielddata*: Heap memory used by Fielddata (e.g., global ordinals or explicitly enabled fielddata on text fields). This is for the same shards, but not a part of Lucene Total.. \n\n+ *Index Writer*: Heap memory used by the Index Writer. This is NOT a part of Lucene Total.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_query_cache_memory_size_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Query Cache"
    },
    {
     "expr": "elasticsearch_indices_request_cache_memory_size_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Request Cache"
    },
    {
     "expr": "elasticsearch_indices_fielddata_memory_size_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Fielddata"
    },
    {
     "expr": "elasticsearch_indices_segments_index_writer_memory_in_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Index Writer"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "JVM Memory Usage - $name",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_max_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\",area=\"heap\"}",
     "legendFormat": "Max heap"
    },
    {
     "expr": "elasticsearch_jvm_memory_used_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\",area=\"heap\"}",
     "legendFormat": "Used heap"
    },
    {
     "expr": "elasticsearch_jvm_memory_used_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\",area=\"non-heap\"}",
     "legendFormat": "Non-Heap"
    },
    {
     "expr": "elasticsearch_jvm_memory_used_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\",area=\"heap\"} / elasticsearch_jvm_memory_max_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\",area=\"heap\"} * 100",
     "legendFormat": "% Used Heap"
    }
   ]
  },
  {
   "title": "JVM GC Runs / s ",
   "type": "graph",
   "description": "Number of JVM GC runs in second by nodes.\nThreshold is 1 GC/s",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 62 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_jvm_gc_collection_seconds_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}} - {{gc}}"
    }
   ]
  },
  {
   "title": "JVM GC Runtime / s ",
   "type": "graph",
   "description": "JVM GC runtime in second by nodes\nThreshold is 40ms / s",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 62 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_jvm_gc_collection_seconds_sum{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[5m]) * 1000",
     "legendFormat": "{{name}} - {{gc}}"
    }
   ]
  },
  { "title": "Documents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Documents Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_docs{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Merged Documents / s",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 69 },
   "yaxes": [
    { "format": "locale", "label": "docs/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_merges_docs_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Deleted Documents",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 69 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_docs_deleted{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Documents Index Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short", "label": "index calls/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Merged Bytes / s",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 74 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_merges_total_size_bytes_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Documents Deleted Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 74 },
   "yaxes": [
    { "format": "locale", "label": "docs/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_docs_deleted{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request cache count - $name",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_request_cache_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "Request Cache"
      }
     ]
    },
    {
     "title": "Request cache size - $name",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 80 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_request_cache_memory_size_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "Request Cache Size"
      }
     ]
    },
    {
     "title": "Request Cache Evictions - $name",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 80 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_request_cache_evictions{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "Request Cache Evictions"
      }
     ]
    },
    {
     "title": "Query cache count - $name",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_query_cache_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "Query Cache"
      }
     ]
    },
    {
     "title": "Query cache size - $name",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 86 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_query_cache_memory_size_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "Query Cache"
      }
     ]
    },
    {
     "title": "Query Cache Evictions - $name",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 86 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_query_cache_evictions{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "Query Cache Evictions"
      }
     ]
    }
   ]
  },
  {
   "title": "Transaction Log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "Translog operations / s",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "locale", "label": "op/s" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_translog_operations{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total Translog Operations",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 81 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_translog_operations{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total Translog Size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 81 },
     "yaxes": [
      { "format": "bytes", "label": "bytes/s" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_translog_size_in_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  { "title": "Thread Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Thread Pool - Queue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum (elasticsearch_thread_pool_queue_count{instance=\"$instance\",cluster=\"$cluster\",name=\"$name\"})",
     "legendFormat": "Queue"
    },
    {
     "expr": "sum(rate(elasticsearch_thread_pool_completed_count{instance=\"$instance\",cluster=\"$cluster\",name=\"$name\"}[$interval]))",
     "legendFormat": "Job/s"
    },
    {
     "expr": "sum (elasticsearch_thread_pool_rejected_count{instance=\"$instance\",cluster=\"$cluster\",name=\"$name\"})",
     "legendFormat": "Reject"
    }
   ]
  },
  {
   "title": "Thread Pool - Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 82 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum (elasticsearch_thread_pool_threads_count{instance=\"$instance\",cluster=\"$cluster\",name=\"$name\"})",
     "legendFormat": "Count"
    },
    {
     "expr": "sum (elasticsearch_thread_pool_largest_count{instance=\"$instance\",cluster=\"$cluster\",name=\"$name\"})",
     "legendFormat": "Largest"
    },
    {
     "expr": "sum (elasticsearch_thread_pool_active_count{instance=\"$instance\",cluster=\"$cluster\",name=\"$name\"})",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Thread Pool - Completed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 82 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum (elasticsearch_thread_pool_completed_count{instance=\"$instance\",cluster=\"$cluster\",name=\"$name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Disk and Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1-\n(elasticsearch_filesystem_data_available_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"} /\nelasticsearch_filesystem_data_size_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"})\n)*100",
     "legendFormat": "{{name}}: {{path}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/sec" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_transport_tx_size_bytes_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: sent"
    },
    {
     "expr": "irate(elasticsearch_transport_rx_size_bytes_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: received"
    }
   ]
  },
  {
   "title": "Disk Read/Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_filesystem_io_stats_device_read_size_kilobytes_sum{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: read"
    },
    {
     "expr": "irate(elasticsearch_filesystem_io_stats_device_write_size_kilobytes_sum{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: write"
    }
   ]
  },
  {
   "title": "Disk Read/Write Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_filesystem_io_stats_device_read_operations_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: read"
    },
    {
     "expr": "irate(elasticsearch_filesystem_io_stats_device_write_operations_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: write"
    }
   ]
  },
  {
   "title": "File Descriptors - $name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_process_open_files_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Open Fds"
    },
    {
     "expr": "elasticsearch_process_max_files_descriptors{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Max Fds"
    },
    {
     "expr": "elasticsearch_process_open_files_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"} / elasticsearch_process_max_files_descriptors{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"} * 100",
     "legendFormat": "% Open Fds"
    }
   ]
  },
  {
   "title": "Segments",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum (elasticsearch_indices_segments_count{instance=\"$instance\",cluster=\"$cluster\",name=\"$name\"})",
     "legendFormat": "Segments"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "OS Load Average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "short", "label": "load1m" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_os_load1{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "OS CPU Usage",
   "type": "graph",
   "description": "% CPU used by OS",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 111 },
   "yaxes": [
    { "format": "percent", "label": "% CPU usage" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_os_cpu_percent{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "description": "% CPU used by process",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 111 },
   "yaxes": [
    { "format": "percent", "label": "% CPU usage" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_process_cpu_percent{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}